motd: A waterfall server.

# Servers:
servers:
  lobby:
    motd: '&1Just another Waterfall - Forced Host'
    address: 127.0.0.1:25566
    restricted: false

priorities:
  - lobby

# Configuration:
host: 0.0.0.0:25565
players: 20
tab_size: 60

ip_forward: false

# Security:
online_mode: true
prevent_proxy_connections: false
