# The name of the server, used for server specific permissions.
#
# - When set to "global" this setting is effectively ignored.
# - In all other cases, the value here is added to all players in a "server" context.
# - See: https://luckperms.net/wiki/Context
server_context: global

# How the plugin should store data
database:

  # - Possible options:
  #
  #   |  Remote databases - require connection information to be configured below
  #   |=> MySQL
  #   |=> MariaDB (preferred over MySQL)
  #   |=> PostgreSQL
  #   |=> MongoDB
  #
  #   |  Flatfile/local database - don't require any extra configuration
  #   |=> H2 (preferred over SQLite)
  #   |=> SQLite
  #
  #   |  Readable & editable text files - don't require any extra configuration
  #   |=> YAML (.yml files)
  #   |=> JSON (.json files)
  #   |=> HOCON (.conf files)
  #   |=> TOML (.toml files)
  #   |
  #   | By default, user, group and track data is separated into different files. Data can be combined
  #   | and all stored in the same file by switching to a combined storage variant.
  #   | Just add '-combined' to the end of the storage-method, e.g. 'yaml-combined'
  method: h2

  # Define the address and port for the database.
  # - The standard DB engine port is used by default
  #   (MySQL: 3306, PostgreSQL: 5432, MongoDB: 27017)
  # - Specify as "host:port" if differs
  address: ''

  # The name of the database to store LuckPerms data in.
  # - This must be created already. Don't worry about this setting if you're using MongoDB.
  database: ''

  # Credentials for the database.
  username: ''
  password: ''
