name: Render
description: Render configuration files.
inputs: {}

runs:
  using: "composite"
  steps:

    # Install Python:
    # Helmaroc is a Python 3 script.
    - uses: actions/setup-python@v3

    # Install Helm:
    # This is used by Helmaroc to render Helm Charts into Minecraft/Bukkit config files.
    - name: Install Helm
      shell: bash
      run: |
        curl -o /tmp/helm.tar.gz 'https://get.helm.sh/helm-v3.9.0-rc.1-linux-amd64.tar.gz'
        tar -xvzf /tmp/helm.tar.gz -C /tmp
        mv /tmp/linux-amd64/helm /usr/local/bin/helm

    # Install PyYAML:
    # This is used by Helmaroc.
    - name: Install Helmaroc Dependencies
      shell: bash
      run: |
        pip3 install pyyaml yamllint

    # Generate the .secrets.yml file, which provides the secrets to helmaroc.
    - name: Generate Secrets
      shell: bash
      run: |
        printf "Secrets:\n" > .secrets.yml
        while read -r envvar; do
          printf "  %s: "%s"\n" "$(cut -d'=' -f1 <<< "$envvar")" "$(cut -d'=' -f2- <<< "$envvar")"
        done < <(env) >> .secrets.yml

    # Render the configuration files.
    - name: Render
      shell: bash
      run: |
        python3 helmaroc.py

    # Lint the rendered configuration files.
    - name: Validate
      shell: bash
      run: |
        yamllint -c .yamllint.ci.yml deploy
